# Generated by Django 5.2.6 on 2025-10-30 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceedd_stream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeinfrastructure',
            name='symbole',
        ),
        migrations.AddField(
            model_name='bailleur',
            name='sigle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='postnom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='unite_monnaie',
            field=models.CharField(blank=True, choices=[('Fc', 'Franc Congolais'), ('$', 'Dollars US'), ('€', 'Euros')], default='Fc', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='typeinfrastructure',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='avenue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='commune',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='quartier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='date_financement',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspecteur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='entite_type',
            field=models.CharField(choices=[('infrastructure', 'Infrastructure'), ('type_infrastructure', 'Type Infrastructure'), ('bailleur', 'Bailleur'), ('zone_contributive', 'Zone contributive'), ('inspection', 'Inspection')], max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('contributeur', 'Contributeur'), ('lecteur', 'Lecteur')], default='lecteur', max_length=20, unique=True),
        ),
    ]
