# Generated by Django 5.2.6 on 2025-11-11 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceedd_stream', '0003_remove_utilisateur_role_remove_photo_entite_id_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
