# Generated by Django 5.2.6 on 2025-11-24 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceedd_stream', '0004_alter_photo_content_type_alter_photo_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('file', models.FileField(upload_to='shapefiles/%Y/%m/%d/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='zonecontributive',
            name='shapefile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ceedd_stream.shp'),
        ),
    ]
