# Generated by Django 6.0 on 2025-12-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceedd_stream', '0005_shp_alter_zonecontributive_shapefile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonecontributive',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='zonecontributive',
            name='superficie',
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
