# Generated by Django 6.0 on 2025-12-29 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceedd_stream", "0006_remove_zonecontributive_geom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="numero_photo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="engagement",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ceedd_stream.client",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="nom",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="type_infrastructure",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ceedd_stream.typeinfrastructure",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="infrastructure",
            unique_together={("client", "nom")},
        ),
    ]
