# Generated by Django 6.0 on 2025-12-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceedd_stream', '0007_photo_numero_photo_alter_infrastructure_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='titre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
