# Generated by Django 6.0 on 2026-01-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ceedd_stream", "0008_client_titre"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="province",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="finance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="finance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="postnom",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="client",
            name="prenom",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="finance",
            name="date_financement",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="url",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("nom", "postnom", "prenom")},
        ),
    ]
